//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAboutMe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oskarprzybylski_users1Entities : DbContext
    {
        public oskarprzybylski_users1Entities()
            : base("name=oskarprzybylski_users1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Entry> Entry { get; set; }
        public virtual DbSet<EntryType> EntryType { get; set; }
        public virtual DbSet<RoleAccess> RoleAccess { get; set; }
    }
}
