//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAboutMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAccess
    {
        public int ID { get; set; }
        public string RoleID { get; set; }
        public int EntryTypeID { get; set; }
        public bool ReadAny { get; set; }
        public bool EditAny { get; set; }
        public bool ReadSelf { get; set; }
        public bool EditSelf { get; set; }
    
        public virtual EntryType EntryType { get; set; }
    }
}
